NewsDotNet.WebUI/Areas/Admin/Controllers/AdminArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsDotNet.DomainModel.Entities;
using NewsDotNet.DomainModel.Abstract;
using NewsDotNet.WebUI.Areas.Admin.Mappers;
using NewsDotNet.WebUI.Areas.Admin.Models;
using Ninject;
using System.Text;
using System.IO;
using Newtonsoft.Json;
using NewsDotNet.WebUI.Infrastracture;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using NewsDotNet.WebUI.Models;
using System.Text.RegularExpressions;

namespace NewsDotNet.WebUI.Areas.Admin.Controllers
{
    [Authorize]
    [DenyBlocked]
    [DenyIfPasswordChangeRequired]
    public class AdminArticlesController : Controller
    {
        private IArticlesRepository _articleRepo;
        private ITagsRepository _tagsRepo;
        private IMapper _modelMapper;

        public AdminArticlesController(IArticlesRepository articleRepo, ITagsRepository tagsRepo, IMapper modelMapper)
        {
            _articleRepo = articleRepo;
            _tagsRepo = tagsRepo;
            _modelMapper = modelMapper;
        }

        public ActionResult List(IEnumerable<int> articleIds)
        {
            //seletct only articles with ids form the list
            var result = _articleRepo.All().Where(article => articleIds.Any(id => id == article.Id)).ToList();

            var jsonSettings = new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

            var convertedResult = JsonConvert.SerializeObject(result, jsonSettings);

            return Content(convertedResult, "application/json");
        }

        public ActionResult PagingList(int page = 1, int itemsPerPage = 10)
        {
            var publishedArticles = _articleRepo.All().Where(a => a.State == ArticleStates.Published);
            var articlesOnPage = publishedArticles.Skip((page - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            var pagingInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = itemsPerPage,
                TotalItems = publishedArticles.Count()
            };

            var result = new ArticleListViewModel
            {
                Articles = articlesOnPage,
                PagingInfo = pagingInfo
            };

            var jsonSettings = new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

            var convertedResult = JsonConvert.SerializeObject(result, jsonSettings);
            return Content(convertedResult, "application/json");
        }

        [HttpGet]
        [Authorize(Roles="User, Editor, Administrator")]
        public ActionResult New()
        {
            var article = new ArticleViewModel();
            ViewBag.Action = ActionType.NewArticle;
            return View("ArticleEditor", article);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User, Editor, Administrator")]
        public async Task<ActionResult> New(ArticleViewModel newArticleView, HttpPostedFileBase titleImage)
        {
            CheckAddressNameAvailability(newArticleView.AddressName, newArticleView.Id);
            if (ModelState.IsValid)
            {
                var article = _modelMapper.Map<ArticleViewModel, Article>(newArticleView);
                article.CreatedTime = DateTime.Now;
                article.LastChangedTime = DateTime.Now;
                article.Tags = TagStringToList(newArticleView.TagsString);
                article.Body = Regex.Replace(article.Body, @"=([0-9])+px", "");
                SaveUploadedImage(article, titleImage);

                var author = await UserManager.FindByNameAsync(User.Identity.Name);
                article.AuthorId = author.Id;

                _articleRepo.Add(article);
                return RedirectToAction("Index", "AdminHome");
            }
            ViewBag.Action = ActionType.NewArticle;
            return View("ArticleEditor", newArticleView);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(string addressName)
        {
            var article = _articleRepo.GetByAddressName(addressName);
            if (null == article)
                return View("Http404", "/Admin" as object);
            if (await UserCanEditArticle(article))
            {
                var articleView = _modelMapper.Map<Article, ArticleViewModel>(article);
                articleView.TagsString = TagListToString(article.Tags);
                ViewBag.Action = ActionType.EditArticle;
                return View("ArticleEditor", articleView); 
            }
            else
            {
                return RedirectToAction("AccessDenied", "AdminHome");
            }
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ArticleViewModel articleView, HttpPostedFileBase titleImage)
        {
            CheckAddressNameAvailability(articleView.AddressName, articleView.Id);
            if (ModelState.IsValid)
            {
                var article = _modelMapper.Map<ArticleViewModel, Article>(articleView);
                if (await UserCanEditArticle(article))
                {
                    article.Tags = TagStringToList(articleView.TagsString);
                    article.LastChangedTime = DateTime.Now;
                    article.Body = Regex.Replace(article.Body, @"=([0-9])+px", "");
                    SaveUploadedImage(article, titleImage);
                    _articleRepo.Update(article);
                    return RedirectToAction("Index", "AdminHome"); 
                }
                else
                {
                    return RedirectToAction("AccessDenied", "AdminHome");
                }
            }
            ViewBag.Action = ActionType.EditArticle;
            return View("ArticleEditor", articleView);
        }

        private string TagListToString(ICollection<Tag> tags)
        {
            if (tags.Count == 0)
                return String.Empty;
            return String.Join<string>(",", tags.Select(tag => tag.Name));
        }

        private ICollection<Tag> TagStringToList(string tagString)
        {
            List<Tag> tags = new List<Tag>();
            if (!String.IsNullOrWhiteSpace(tagString))
            {
                var tagArray = tagString.Split(',');
                foreach (var s in tagArray)
                {
                    if (!String.IsNullOrWhiteSpace(s))
                    {
                        string name = s.Trim();
                        Tag t = _tagsRepo.GetByName(name);
                        if (null == t)
                        {
                            t = _tagsRepo.Add(new Tag { Name = name, AddressName = name });
                        }
                        tags.Add(t);
                    }
                }
            }
            return tags;
        }

        private void SaveUploadedImage(Article article, HttpPostedFileBase image)
        {
            string newPath;
            string oldPath = article.TitleImagePath;
            bool pathChanged = !isOldImagePathRelevant(oldPath, article.AddressName);
            FileInfo oldImageInfo = null;
            if (pathChanged)
                oldImageInfo = new FileInfo(Server.MapPath(oldPath));
            if (null == image)
            {
                if (pathChanged)
                {   //there is an old image and article address changed => rename old image
                    newPath = String.Format("~/Content/Images/Articles/{0}{1}",
                                        article.AddressName,
                                        oldImageInfo.Extension);
                    oldImageInfo.MoveTo(Server.MapPath(newPath));
                }
                else
                {
                    if (null == oldPath)
                        article.TitleImagePath = "";
                    return;
                }
            }
            else
            {   //there is a new image => save new image
                FileInfo newImageInfo = new FileInfo(image.FileName);
                newPath = String.Format("~/Content/Images/Articles/{0}{1}",
                                            article.AddressName,
                                            newImageInfo.Extension);
                image.SaveAs(Server.MapPath(newPath));

                if (pathChanged)
                {   //path changed and there is an old image => delete old image
                    oldImageInfo.Delete();
                }
            }
            article.TitleImagePath = newPath;
        }

        public JsonResult ValidateAddressNameAvailability(string AddressName, int Id)
        {
            if (isAddressNameAvailable(AddressName, Id))
                return Json("true", JsonRequestBehavior.AllowGet);
            else
                return Json(String.Format("Адрес {0} уже принадлежит другой статье", AddressName), JsonRequestBehavior.AllowGet);
        }

        private void CheckAddressNameAvailability(string addressName, int id)
        {
            if (!isAddressNameAvailable(addressName, id))
                ModelState.AddModelError("addressName", String.Format("Адрес {0} уже принадлежит другой статье", addressName));
        }

        private bool isAddressNameAvailable(string addressName, int id)
        {
            var existingArticle = _articleRepo.GetByAddressName(addressName);
            return (null == existingArticle || existingArticle.Id == id);
        }

        private bool isOldImagePathRelevant(string imagePath, string articleAddressName)
        {
            if (String.IsNullOrEmpty(imagePath))
                return true;
            FileInfo info = new FileInfo(imagePath);
            string name = info.Name.Remove(info.Name.LastIndexOf('.'));
            return name.Equals(articleAddressName);
        }

        public async Task<ContentResult> Articles(JqInViewModel jqParams)
        {
  

NewsDotNet.WebUI/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsDotNet.DomainModel.Entities;
using NewsDotNet.DomainModel.Abstract;
using NewsDotNet.WebUI.Models;
using System.Globalization;
using NewsDotNet.WebUI.Infrastracture;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;


namespace NewsDotNet.WebUI.Controllers
{
    public class ArticlesController : Controller
    {
        private IArticlesRepository _articleRepo;
        private ITagsRepository _tagsRepo;
        private IMainPageEntitiesRepository _mainPageRepo;
        
        public ArticlesController(IArticlesRepository articleRepo, ITagsRepository tagRepo, IMainPageEntitiesRepository mainPageRepo)
        {
            _articleRepo = articleRepo;
            _tagsRepo = tagRepo;
            _mainPageRepo = mainPageRepo;
        }
        
        public async Task<ActionResult> Show(string addressName)
        {
            var article = _articleRepo.GetByAddressName(addressName);
            if (null == article)
                return View("Http404", "/" as object);

            var userManager = HttpContext.GetOwinContext().GetUserManager<IdentityUserManager>();
            var user = await userManager.FindByNameAsync(User.Identity.Name);

            bool canUserSeeDraftedArticle = user != null &&
                (!User.IsInRole("User") || user.Id == article.AuthorId);

            if (article.State == ArticleStates.Deleted ||
                article.State == ArticleStates.Draft && !canUserSeeDraftedArticle)
                    return View("Http404", "/" as object);

            article.Body = ParserSingletone.ToHtml(article.Body);
            return View("Article", article);
        }
       
     public ActionResult Archive(string search){
            var mainPageArticles = _mainPageRepo.All().Select(e => e.Article);
            var articles = _articleRepo.All()
                .Where(a => a.State == ArticleStates.Published && !mainPageArticles.Contains(a))
                .OrderByDescending(a => a.CreatedTime)
                .GroupBy(a => a.CreatedTime.ToShortDateString())
                .Select(group => new ArchiveArticles { Date = group.Key, Articles = group.ToList() });
            return View("ArchiveView",articles);
        }
        public ActionResult ArticlesWithTag(string tagAddressName, int page = 1)
        {
            var tag = _tagsRepo.All().Where(t => t.AddressName == tagAddressName).FirstOrDefault();
            IEnumerable<Article> articles;

            if (tag == null)
            {
                articles = new List<Article>();
            }
            else
            {
                articles = tag.Articles.Where(a => a.State == ArticleStates.Published);
            }

            var oftenTag = articles.SelectMany(article => article.Tags)
                            .Where(t => t.ID != tag.ID)
                            .GroupBy(t => t.ID)
                            .OrderByDescending(group => group.Count())
                            .Select(group => group.First())
                            .FirstOrDefault();

            if (oftenTag != null)
            {
                ViewBag.MostOftenTagAddressName = oftenTag.AddressName;
                ViewBag.MostOftenTagName = oftenTag.Name;
            }

            PagingInfo pagingInfo = new PagingInfo
            {
                CurrentPage = page,
                TotalItems = articles.Count(),
                ItemsPerPage = 10
            };
            ViewBag.Title = String.Format("Статьи с тегом {0}", tag.Name);
            ViewBag.TagAddressName = tag.AddressName;
            ViewBag.TagName = tag.Name;

            var result = new ArticleListViewModel
            {
                Articles = articles
                .Skip(pagingInfo.ItemsPerPage * (pagingInfo.CurrentPage - 1))
                .Take(pagingInfo.ItemsPerPage)
                .ToList(),
                PagingInfo = pagingInfo
            };

            return View(result);
        }
        public ActionResult ArticlesForSearch(string search)
        {
            var keywords = search.Split(new []{' '}, StringSplitOptions.RemoveEmptyEntries).Select(word => word.ToLower());

            var keywordMatch = _articleRepo.All().Where(a => 
                a.State == ArticleStates.Published && 
                keywords.Any(kw => 
                    a.Title.ToLower()
                    .Contains(kw) || 
                    a.Body.Contains(kw)))
                    .ToList();

            var tagsMatch = _tagsRepo.All()
                .Where(tag => keywords.Any(kw => tag.Name.ToLower().Contains(kw))).ToList()
                .SelectMany(tag => tag.Articles.ToList());

            IEnumerable<Article> dateMatch = new List<Article>();

            DateTime searchDate;

            var cultureName = Request.UserLanguages.FirstOrDefault() ?? "ru-RU";
            CultureInfo culture;

            try
            {
                culture = CultureInfo.CreateSpecificCulture(cultureName);
            }
            catch(CultureNotFoundException)
            {
                culture = CultureInfo.CreateSpecificCulture("ru-RU");
            }

            bool isDate = DateTime.TryParse(search, culture, DateTimeStyles.None, out searchDate);

            var articles = keywordMatch.Concat(tagsMatch);

            if(isDate)
            {
                dateMatch = _articleRepo.All().Where(a => a.CreatedTime.Date == searchDate.Date);
                articles = articles.Concat(dateMatch);
            }

            articles = articles
                .Where(a => a.State == ArticleStates.Published)
                .GroupBy(a => a.Id)
                .OrderBy(group => group.Count())
                .Select(group => group.First())
                .ToList();

            return PartialView(articles);
        }

        public ActionResult ArticleAuthorInit()
        {
            var userManager = HttpContext.GetOwinContext().GetUserManager<IdentityUserManager>();

            var author = userManager.Users.FirstOrDefault();
            var articles = _articleRepo.All().Where(a => a.AuthorId == null).ToList(); 
            
            if(author != null)
            {
                articles.ForEach(a => {
                    a.AuthorId = author.Id;
                    _articleRepo.Update(a);
                });
            }

            return RedirectToAction("Index","Home");
        }

        public async Task<ActionResult> ArticlesByAuthor(string authorName, int page = 1)
        {
            var userManager = HttpContext.GetOwinContext().GetUserManager<IdentityUserManager>();
            var author = await userManager.FindByNameAsync(authorName);
            if (null == author)
                return View("Author", null);
            var articles = _articleRepo.All()
                .Where(article => article.AuthorId.Equals(author.Id) &&
                       article.State == ArticleStates.Published)
                .OrderByDescending(article => article.CreatedTime);


            PagingInfo pagingInfo = new PagingInfo
            {
                CurrentPage = page,
                TotalItems = articles.Count(),
                ItemsPerPage = 10
            };

            ViewBag.AuthorName = authorName;
            ViewBag.AuthorFirstName = author.FirstName;
            ViewBag.AuthorLastName = author.LastName;

            var result = new ArticleListViewModel
            {
                Articles = articles
                .Skip(pagingInfo.ItemsPerPage * (pagingInfo.CurrentPage - 1))
                .Take(pagingInfo.ItemsPerPage)
                .ToList(),
                PagingInfo = pagingInfo
            };

            return View("Author", result);
        }
      
	}
}

NewsDotNet.WebUI/Areas/Admin/Views/AdminArticles/ArticleEditor.cshtml
@using NewsDotNet.WebUI.Areas.Admin.Controllers
@model NewsDotNet.WebUI.Areas.Admin.Models.ArticleViewModel

@{
    ActionType action = ViewBag.Action;
    ViewBag.Title = action == ActionType.NewArticle ? "Новая статья" : "Редактирование статьи";
}

@using (Html.BeginForm(action == ActionType.NewArticle ? "New" : "Edit",
                        "AdminArticles",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal container">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CreatedTime)
        @Html.HiddenFor(model => model.TitleImagePath)
        @Html.HiddenFor(model => model.State)
        @Html.HiddenFor(model => model.AuthorId)
        
        @{bool isImagePresent = !String.IsNullOrEmpty(Model.TitleImagePath);}

        <div class="form-group">
            <label class="control-label col-md-2">Заголовок</label>
            <div class="col-md-9">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Адрес</label>
            <div class="col-md-9">
                @Html.EditorFor(model => model.AddressName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Изображение</label>
            <div class="col-md-9">
                <div class="row" id="previewRow" @if (!isImagePresent) { <text> hidden="true" </text> }>
                    <div class="col-xs-3">
                        <img id="uploadPreview" width="100%" 
                             @if (isImagePresent) { <text> src="@Url.Content(Model.TitleImagePath)" </text>  } />
                    </div>
                </div>
                <div class="input-group">
                    <span class="input-group-btn">
                        <span class="btn btn-primary btn-file">
                            Выберите файл...
                            <input type="file" name="titleImage" id="titleImage" accept=".jpg,.png,.jpeg,.gif" onchange="PreviewImage();" />
                        </span>
                    </span>
                    <input type="text" id="titleText" class="form-control" readonly>
                </div>
                @Html.ValidationMessageFor(model => model.TitleImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Тело статьи</label>
            <div class="col-md-9">
                @Html.TextAreaFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Теги</label>
            <div class="col-md-9">
                @Html.EditorFor(model => model.TagsString, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.TagsString, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-9">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index", "AdminHome")
</div>

<script src="~/Content/ckeditor/ckeditor.js"></script>
<script src="~/Content/jquery-tags-input/jquery.tagsinput.min.js"></script>
<script src="~/Scripts/bootstrap-maxlength.min.js"></script>
<script src="~/Scripts/jquery-ui-1.11.4.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/article-editor.js"></script>
<link rel="stylesheet" type="text/css" href="~/Content/Styles/jquery-ui-1.11.4.min.css" />
<link rel="stylesheet" type="text/css" href="~/Content/jquery-ui-1.9.2.custom/css/black-tie/jquery-ui-1.9.2.custom.css" />
<link rel="stylesheet" type="text/css" href="~/Content/jquery-tags-input/jquery.tagsinput.min.css" />
<link rel="stylesheet" href="~/Content/Styles/article-editor.css" />

NewsDotNet.WebUI/Areas/Admin/Views/AdminArticles/DeletedArticles.cshtml
@using NewsDotNet.WebUI.Infrastracture
@model IEnumerable<NewsDotNet.DomainModel.Entities.Article>

@{
    ViewBag.Title = "Удаленные статьи";
}


<div class="container">
       <h2>Удаленные статьи</h2>
    @if (@Model.Count() == 0)
{
    <div class="alert alert-info">Нет статей для отображения</div>
}

    <a href="~/Areas/Admin/Views/AdminArticles/DeletedArticles.cshtml">~/Areas/Admin/Views/AdminArticles/DeletedArticles.cshtml</a>
@foreach (var article in Model)
{
    <div class="panel panel-info" onclick="location.href='@Url.Action("Show", "Articles", new {area = "", addressName = article.AddressName })';">
                <div class="panel-heading">
                        <h4 class="panel-title">
                                @article.Title
            </h4>
        </div>
                <div class="panel-body">
                        @Html.Raw(ParserSingletone.ToHtml(article.Body.Substring(0, Math.Min(article.Body.Length, 100))) + "...")
            
        </div>
                <div class="panel-footer">
                        Автор: Аноним
        </div>
    </div>
   }
</div>