NewsDotNet.WebUI/Areas/Admin/Controllers/IssueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsDotNet.WebUI.Infrastracture;
using NewsDotNet.DomainModel.Entities;
using NewsDotNet.DomainModel.Abstract;

namespace NewsDotNet.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles="Administrator, Editor")]
    [DenyBlocked]
    [DenyIfPasswordChangeRequired]
    public class IssueController : Controller
    {
        IMainPageEntitiesRepository _mainPageRepo;
        IArticlesRepository _articlesRepo;

        public IssueController(IMainPageEntitiesRepository mainPageRepo, IArticlesRepository articlesRepo)
        {
            _mainPageRepo = mainPageRepo;
            _articlesRepo = articlesRepo;
        }
        //
        // GET: /Admin/Issue/
        public ActionResult Index()
        {
            return View(_mainPageRepo.All().Where(e => !e.IsFeatured).ToList());
        }


        [HttpPost]
        public ActionResult Save(IEnumerable<MainPageEntity> newEntities)
        {
            _mainPageRepo.Refill(newEntities);
            return new JsonResult { Data = new { result = "OK" } };
        }
	}
}

NewsDotNet.WebUI/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using NewsDotNet.WebUI.Infrastracture;
using NewsDotNet.DomainModel.Entities;
using Newtonsoft.Json;
using NewsDotNet.WebUI.Areas.Admin.Models;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using NewsDotNet.WebUI.Areas.Admin.Mappers;
using System.Reflection;
using System.Security.Claims;
using Microsoft.Owin.Security;

namespace NewsDotNet.WebUI.Areas.Admin.Controllers
{
    [Authorize]
    [DenyBlocked]
    [DenyIfPasswordChangeRequired]
    public class UsersController : Controller
    {
        private IMapper _mapper;

        public UsersController(IMapper mapper)
        {
            _mapper = mapper;
        }

        //
        // GET: /Admin/Users/
        [Authorize(Roles="Administrator")]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> List()
        {
            var currentUser = await UserManager.FindByNameAsync(User.Identity.Name);
            var userList = (from user in UserManager.Users.Where(user => user.Id != currentUser.Id).ToList()
                            select _mapper.Map<User, UserListViewModel>(user)).ToList();
            userList.ForEach(model => model.Role = IdentityRoleManager.UserRoles.FirstOrDefault(role => UserManager.IsInRole(model.Id, role)));
            userList.ForEach(model => model.IsBlocked = UserManager.IsInRole(model.Id, "Blocked"));
            var jsonSettings = new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };
            var result = JsonConvert.SerializeObject(userList, jsonSettings);
            return Content(result, "application/json");
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult GetUserInfo(string id)
        {
            var user = UserManager.Users.FirstOrDefault(u => u.Id == id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var result = _mapper.Map<User, UserListViewModel>(user);
            result.Role = IdentityRoleManager.UserRoles.FirstOrDefault(role => UserManager.IsInRole(result.Id, role));
            var convertedResult = JsonConvert.SerializeObject(result);
            return Content(convertedResult, "application/json");
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Create(CreateUserModel newUser)
        {
            string response;
            if(newUser.Password != newUser.PasswordConfirm)
            {
                ModelState.AddModelError("Password", "Введенные пароли не совпадают");
            }

            if(!IdentityRoleManager.UserRoles.Any(role => role == newUser.Role))
            {
                ModelState.AddModelError("Role", "Выбранная роль не существует");
            }
            if (ModelState.IsValid)
            {
                var user = _mapper.Map<CreateUserModel, User>(newUser);
                IdentityResult result = await UserManager.CreateAsync(user, newUser.Password);
                if(result.Succeeded)
                {
                    var createdUser = await UserManager.FindByNameAsync(newUser.UserName);
                    result = await UserManager.AddToRolesAsync(createdUser.Id, new string[] { newUser.Role, "RequirePasswordChange" });

                    if(result.Succeeded)
                    {
                        var createdUserModel = _mapper.Map<User, UserListViewModel>(createdUser);
                        createdUserModel.Role = IdentityRoleManager.UserRoles.FirstOrDefault(role => UserManager.IsInRole(createdUserModel.Id, role));

                        response = JsonConvert.SerializeObject(new
                        {
                            Result = "success",
                            User = createdUserModel
                        });
                        return Content(response, "application/json");
                    }
                    else
                    {
                        UserManager.Delete(createdUser);
                        AddErrorsFromResult(result);
                    }
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }

            var errors = ModelState.Where(item=> item.Value.Errors.Any()).ToDictionary(
                    item => item.Key,
                    item => item.Value.Errors.Select(e => e.ErrorMessage).ToList()
                );

            response = JsonConvert.SerializeObject(new
            {
                Result = "error",
                Errors = errors
            });
            return Content(response, "application/json");
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult IsUserNameAvailable(string userName)
        {
            bool result = !UserManager.Users.Any(user => user.UserName == userName);
            return Json(result);
        }

        public ActionResult GetRoleList()
        {
            var displayNames = new List<string> { "Автор", "Корректор", "Редактор", "Администратор" };
            var result = IdentityRoleManager.UserRoles.Zip(displayNames, (r, d) => new { value = r, text = d });
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> InlineUpdate(string name, string pk, string value)
        {
            string status;
            string msg;

            var whiteList = new[] { "FirstName", "LastName", "Email" };

            var user = UserManager.FindById(pk);
            if(user == null)
            {
                status = "error";
                msg = "Пользователь с таким ID не найден";
            }
            else
            {
                PropertyInfo propertyInfo = user.GetType().GetProperty(name);
                if(!whiteList.Contains(name) || propertyInfo == null)
                {
                    status = "error";
                    msg = "Свойство с таким именем не найдено";
                }
                else
                {
                    Type t = propertyInfo.PropertyType;
                    object convertedValue;
                    convertedValue = Convert.ChangeType(value, t);
                    propertyInfo.SetValue(user, convertedValue);

                    IdentityResult result = await UserManager.UpdateAsync(user);

                    if (result.Succeeded)
                    {
                        status = "success";
                        msg = "Record updated";
                    }
                    else
                    {
                        status = "error";
                        msg = String.Join(",", result.Errors);
                    }
                }
            }
            return Json(new { status = status, msg = msg });
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> InlineRoleChange(string name, string pk, string value)
        {
            string status;
            string msg;

            var user = UserManager.FindById(pk);
            var admin = UserManager.FindByName(User.Identity.Name);
            if (user == null)
            {
                status = "error";
                msg = "Пользователь с таким ID не найден";
            }
            else if (!IdentityRoleManager.UserRoles.Any(role => role == value))
            {
                status = "error";
                msg = "Выбранная роль не найдена";
            }
            else if (admin.Id.Equals(pk))
            {
                status = "error";
                msg = "Вы не можете изменить свою роль";
            }
            else
            {
                if(UserManager.IsInRole(pk, value))
                {
                    status = "error";
                    msg = "Пользователь уже в выбранной роли";
                }
                else
                {
                    IdentityResult result;

                    result = await UserManager.RemoveFromRolesAsync(user.Id, IdentityRoleManager.UserRoles.Where(role => UserManager.IsInRole(user.Id, role)).ToArray());
                    if(result.Succeeded)
                    {
                        result = await UserManager.AddToRoleAsync(user.Id, value);
                        if(result.Succeeded)
                        {
                            status = "success";
                            msg = "Record updated";
                        }
                        else
                        {
                            status = "error";
                            msg = String.Join(",", result.Errors);
                        }
                    }
                    else
                    {
                        status = "error";
                        msg = String.Join(",", result.Errors);
                    }
                }
            }
            return Json(new { status = status, msg = msg });
        }

        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult Login(string returnUrl)
        {
            if(User.Identity.IsAuthenticated)
            {
                //If logged user tried to access login page directly by himself
                if(String.IsNullOrEmpty(returnUrl))
                {
                    return Redirect(Url.Action("Index", "AdminHome"));
                }
                //User was redirected to this page from other page he don't have access to
                else
                {
                    return Redirect(Url.Action("AccessDenied", "AdminHome"));
                }
            }

NewsDotNet.WebUI/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>

    <head>
        <title>@ViewBag.Title</title>
        <link href="~/Content/Styles/bootstrap.min.css" rel="stylesheet" />
        <link href="~/Content/Styles/AdminStyles.css" rel="stylesheet" />
        <link rel="shortcut icon" type="image/x-icon" href="~/Content/Images/Layout/fav-icon.png" />
        <script src="~/Scripts/jquery-1.10.2.min.js"></script> 
        <script src="~/Scripts/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-inverse" role="navigation">
                    <div class="navbar-header">
                        <a class="navbar-brand" href=@Url.Action("Index", "AdminHome")>
                            News.Net Admin
                        </a>
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#responsive-menu">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                        <div class="collapse navbar-collapse" id="responsive-menu">
                            @if(User.Identity.IsAuthenticated)
                            {
                                <ul class="nav navbar-nav">
                                    <li><a href="@Url.Action("Index", "AdminHome")">Статьи и Теги</a></li>
                                    @if(User.IsInRole("Editor") || User.IsInRole("Administrator"))
                                    {
                                        <li><a href="@Url.Action("Index", "Issue")">Формирование выпуска</a></li>
                                    }
                                    @if (User.IsInRole("Administrator"))
                                    {
                                        <li><a href="@Url.Action("Index","Users")">Пользователи</a></li>
                                    }                                                                                                      

                                    <li class="pull-right">
                                        <a id="user" role="button" data-toggle="popover">
                                            @User.Identity.Name <span class="glyphicon glyphicon-user"></span>
                                        </a>
                                    </li>
                                </ul>
                            }                      
                        </div>
                </nav>
        </div>

        <div id="alert-box" role="alert">

        </div>

        <div class="container">
            @RenderBody()
        </div>
        <br>
        <script type="text/javascript">
            $(document).ready(function () {
                $('#user').popover({
                    placement: 'bottom',
                    html: true,
                    content: '@Html.Action("UserPopup", "Users")',
                    title: "Вы вошли как:",
                    container: 'body'
                })
                $('body').bind('mousedown', function (e) {
                    if ($('#user').attr('aria-describedby')) {
                        if ($(e.target).parents('div.popover').length <= 0 &&
                            e.target.id != 'user' &&
                            e.target.parentElement.id != 'user') {
                                $('#user').popover('hide');
                        }
                    }
                })
            })
        </script>
    </body>
</html>