NewsDotNet.WebUI/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsDotNet.DomainModel.Entities;
using NewsDotNet.DomainModel.Abstract;
using NewsDotNet.WebUI.Models;
using System.Globalization;
using NewsDotNet.WebUI.Infrastracture;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;


namespace NewsDotNet.WebUI.Controllers
{
    public class ArticlesController : Controller
    {
        private IArticlesRepository _articleRepo;
        private ITagsRepository _tagsRepo;
        private IMainPageEntitiesRepository _mainPageRepo;
        
        public ArticlesController(IArticlesRepository articleRepo, ITagsRepository tagRepo, IMainPageEntitiesRepository mainPageRepo)
        {
            _articleRepo = articleRepo;
            _tagsRepo = tagRepo;
            _mainPageRepo = mainPageRepo;
        }
        
        public async Task<ActionResult> Show(string addressName)
        {
            var article = _articleRepo.GetByAddressName(addressName);
            if (null == article)
                return View("Http404", "/" as object);

            var userManager = HttpContext.GetOwinContext().GetUserManager<IdentityUserManager>();
            var user = await userManager.FindByNameAsync(User.Identity.Name);

            bool canUserSeeDraftedArticle = user != null &&
                (!User.IsInRole("User") || user.Id == article.AuthorId);

            if (article.State == ArticleStates.Deleted ||
                article.State == ArticleStates.Draft && !canUserSeeDraftedArticle)
                    return View("Http404", "/" as object);

            article.Body = ParserSingletone.ToHtml(article.Body);
            return View("Article", article);
        }
       
     public ActionResult Archive(string search){
            var mainPageArticles = _mainPageRepo.All().Select(e => e.Article);
            var articles = _articleRepo.All()
                .Where(a => a.State == ArticleStates.Published && !mainPageArticles.Contains(a))
                .OrderByDescending(a => a.CreatedTime)
                .GroupBy(a => a.CreatedTime.ToShortDateString())
                .Select(group => new ArchiveArticles { Date = group.Key, Articles = group.ToList() });
            return View("ArchiveView",articles);
        }
        public ActionResult ArticlesWithTag(string tagAddressName, int page = 1)
        {
            var tag = _tagsRepo.All().Where(t => t.AddressName == tagAddressName).FirstOrDefault();
            IEnumerable<Article> articles;

            if (tag == null)
            {
                articles = new List<Article>();
            }
            else
            {
                articles = tag.Articles.Where(a => a.State == ArticleStates.Published);
            }

            var oftenTag = articles.SelectMany(article => article.Tags)
                            .Where(t => t.ID != tag.ID)
                            .GroupBy(t => t.ID)
                            .OrderByDescending(group => group.Count())
                            .Select(group => group.First())
                            .FirstOrDefault();

            if (oftenTag != null)
            {
                ViewBag.MostOftenTagAddressName = oftenTag.AddressName;
                ViewBag.MostOftenTagName = oftenTag.Name;
            }

            PagingInfo pagingInfo = new PagingInfo
            {
                CurrentPage = page,
                TotalItems = articles.Count(),
                ItemsPerPage = 10
            };
            ViewBag.Title = String.Format("Статьи с тегом {0}", tag.Name);
            ViewBag.TagAddressName = tag.AddressName;
            ViewBag.TagName = tag.Name;

            var result = new ArticleListViewModel
            {
                Articles = articles
                .Skip(pagingInfo.ItemsPerPage * (pagingInfo.CurrentPage - 1))
                .Take(pagingInfo.ItemsPerPage)
                .ToList(),
                PagingInfo = pagingInfo
            };

            return View(result);
        }
        public ActionResult ArticlesForSearch(string search)
        {
            var keywords = search.Split(new []{' '}, StringSplitOptions.RemoveEmptyEntries).Select(word => word.ToLower());

            var keywordMatch = _articleRepo.All().Where(a => 
                a.State == ArticleStates.Published && 
                keywords.Any(kw => 
                    a.Title.ToLower()
                    .Contains(kw) || 
                    a.Body.Contains(kw)))
                    .ToList();

            var tagsMatch = _tagsRepo.All()
                .Where(tag => keywords.Any(kw => tag.Name.ToLower().Contains(kw))).ToList()
                .SelectMany(tag => tag.Articles.ToList());

            IEnumerable<Article> dateMatch = new List<Article>();

            DateTime searchDate;

            var cultureName = Request.UserLanguages.FirstOrDefault() ?? "ru-RU";
            CultureInfo culture;

            try
            {
                culture = CultureInfo.CreateSpecificCulture(cultureName);
            }
            catch(CultureNotFoundException)
            {
                culture = CultureInfo.CreateSpecificCulture("ru-RU");
            }

            bool isDate = DateTime.TryParse(search, culture, DateTimeStyles.None, out searchDate);

            var articles = keywordMatch.Concat(tagsMatch);

            if(isDate)
            {
                dateMatch = _articleRepo.All().Where(a => a.CreatedTime.Date == searchDate.Date);
                articles = articles.Concat(dateMatch);
            }

            articles = articles
                .Where(a => a.State == ArticleStates.Published)
                .GroupBy(a => a.Id)
                .OrderBy(group => group.Count())
                .Select(group => group.First())
                .ToList();

            return PartialView(articles);
        }

        public ActionResult ArticleAuthorInit()
        {
            var userManager = HttpContext.GetOwinContext().GetUserManager<IdentityUserManager>();

            var author = userManager.Users.FirstOrDefault();
            var articles = _articleRepo.All().Where(a => a.AuthorId == null).ToList(); 
            
            if(author != null)
            {
                articles.ForEach(a => {
                    a.AuthorId = author.Id;
                    _articleRepo.Update(a);
                });
            }

            return RedirectToAction("Index","Home");
        }

        public async Task<ActionResult> ArticlesByAuthor(string authorName, int page = 1)
        {
            var userManager = HttpContext.GetOwinContext().GetUserManager<IdentityUserManager>();
            var author = await userManager.FindByNameAsync(authorName);
            if (null == author)
                return View("Author", null);
            var articles = _articleRepo.All()
                .Where(article => article.AuthorId.Equals(author.Id) &&
                       article.State == ArticleStates.Published)
                .OrderByDescending(article => article.CreatedTime);


            PagingInfo pagingInfo = new PagingInfo
            {
                CurrentPage = page,
                TotalItems = articles.Count(),
                ItemsPerPage = 10
            };

            ViewBag.AuthorName = authorName;
            ViewBag.AuthorFirstName = author.FirstName;
            ViewBag.AuthorLastName = author.LastName;

            var result = new ArticleListViewModel
            {
                Articles = articles
                .Skip(pagingInfo.ItemsPerPage * (pagingInfo.CurrentPage - 1))
                .Take(pagingInfo.ItemsPerPage)
                .ToList(),
                PagingInfo = pagingInfo
            };

            return View("Author", result);
        }
      
	}
}

NewsDotNet.WebUI/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsDotNet.DomainModel.Abstract;
using NewsDotNet.DomainModel.Entities;

namespace NewsDotNet.WebUI.Controllers
{
    public class TagsController : Controller
    {
        ITagsRepository _tagRepo;

        public TagsController(ITagsRepository tagRepo)
        {
            _tagRepo = tagRepo;
        }
        /// <summary>
        /// list of all tags in repository
        /// </summary>
        public PartialViewResult TagsCloud()
        {
            ///throw new NotImplementedException();
            return PartialView(_tagRepo.All().ToList());
        }
	}
}

NewsDotNet.WebUI/Views/Shared/Http404.cshtml
@model string
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Страница не найдена</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/Images/Layout/fav-icon.png" />
</head>
<body>
    <div class="container">
        <div class="row vertical-center-row">
            <div class="col-lg-12">
                <div class="row ">
                    <div class="col-xs-6 col-xs-offset-3">
                        <div class="plate">
                            <p class="plate-text">404</p>
                        </div>
                        <center>
                            <h4>Запрашиваемая Вами страница не найдена</h4>
                            <p><a href="@Model" class="btn btn-primary">Вернуться на главную</a></p>
                        </center>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <link href="~/Content/Styles/bootstrap.min.css" rel="stylesheet" />
    <style>
        html, body, .container {
            height: 100%;
            background-color: #ff6767;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

        .container {
            display: table;
            vertical-align: middle;
        }

        .vertical-center-row {
            display: table-cell;
            vertical-align: middle;
        }

        div.plate {
            background-color: #fff;
            border-radius: 10px;
            padding: 10px;
        }

        p.plate-text {
            color: #d01717;
            font-size: 72px;
            text-align: center;
        }
    </style>

</body>
</html>

NewsDotNet.WebUI/Views/Shared/_Disqus.cshtml
@model NewsDotNet.DomainModel.Entities.Article

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'newsdotnet';
    var disqus_identifier = '@Model.AddressName';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

NewsDotNet.WebUI/Views/Shared/_DisqusCommentCount.cshtml
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'newsdotnet';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>

NewsDotNet.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="~/Content/Styles/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/Images/Layout/fav-icon.png" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!----//webfonts---->
    <!-- Global CSS for the page and tiles -->
    <link rel="stylesheet" href="~/Content/Styles/main.css">
    <!-- //Global CSS for the page and tiles -->
    <!--Start-click-menu-->
    <script src="~/Scripts/jquery-1.10.2.js"></script> 
    <!-- Bootstrap CSS file -->
    <!--<script src="~/Scripts/bootstrap.min.js"></script>-->
    <link href="~/Content/Styles/bootstrap.min.css" rel="stylesheet" />
    <!-- CSS file for menu -->
    <link href="~/Content/Styles/styleformenu.css" rel='stylesheet' type='text/css' />
    <!--//End-click-menu-->
</head>
<body>
    <!---start-wrap---->
    <!---start-header---->
    <div class="header">
        <div class="wrap">
            <div class="logo">
                <a href="@Url.Action("Index", "Home")"><img src="@Url.Content("~/Content/Images/Layout/logo-header.png")" /></a>
            </div>
            @* INCLUDE SiteBarMenu *@
            @Html.Partial("_SiteBarMenu")
            <div class="top-searchbar">
                <form action="@Url.Action("ArticlesForSearch","Articles")" method="post" id="searchForm">
                    <input type="text" name="search" /><input type="submit" value="" />
                </form>
            </div>
            <div class="clear"> </div>
        </div>
    </div>
    <!---//End-header---->
    <!---start-content---->
    <div id="search-results-block">
        <span class="glyphicon glyphicon-remove" id="searchCloseBtn" aria-hidden="true"></span>
        <div id="search-results">

        </div>
    </div>
    <div class="content">
        @RenderBody()
        <br>
    </div>
    <!----start-footer--->
    <div class="footer">
        <a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"></span></a>
    </div>
    <!----//End-footer--->
    <!---//End-wrap---->
    <!-- js file for menu -->
    <script src='~/Scripts/jquery.formenu.js' type='text/javascript'></script>
    <script src="~/Scripts/jquery.form.min.js"></script>
    <script src="~/Scripts/ArticleSearch.js"></script>
</body>
</html>

NewsDotNet.WebUI/Views/Shared/_SiteBarMenu.cshtml
<!--navigation button-->
<div class='main-nav white-bg'>
    <div class='mobile-toggle'>
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
<!--menu box start-->
<section class='menu-panel fullheight'>
    <div class='row'>
        <article class='col-md-6 fullheight'>
            <div class='valign text-center slogan-holder'>
                <div class='nav-logo-wrap'>
                    <a href='#'>
                        <img alt="NewsDotNet" src="~/Content/Images/Layout/logo.png" />
                    </a>
                    <div class='slogan-wrap'>
                        <h3 class='white font3 slogan-text'>News.Net Co. Working hard</h3>
                    </div>
                </div>
            </div>
        </article>
        <article class='col-md-6 fullheight nav-list-holder white-bg'>
            <div class='valign'>
                <nav class='nav-item-wrap'>
                    <ul class='main-nav-menu main-nav-menu-effect' id='menu-menu-1'>
                        <li><a href="@Url.Action("Index", "Home")"><span>Главная</span></a></li>
                        <li><a href="@Url.Action("Archive", "Articles")"><span>Архив</span></a></li>
                    </ul>
                </nav>
                <div class='copy-credits'>
                </div>
                @* INCLUDE TagsCloud *@
                @Html.Action("TagsCloud", "Tags")
            </div>
        </article>
    </div>
</section>
<!--menu box end-->